baseURL: https://www.damygectrl.com/
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: red
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 10
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  # favicon 
  favicon: /favicon.ico
  # reading time estimates
  readingTime: true


languages:
  en:
    languageName: English
    title: Damyge Ctrl
    subtitle: Damyge Ctrl is Damyge's cybersecurity blog. Find writeups, stories, guides, and more.
    keywords: Damyge, Ctrl, Damage, Control, Damage Ctrl, Damage Control, DamygeCtrl, DamageControl
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Other Posts
    commentSection: Comments
    shareSection: Share

    params:
      logo:
        logoText: Damyge Ctrl
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: credits
        name: Credits
        url: /credits
      - identifier: rss
        name: RSS
        url: /index.xml



markup:
  goldmark:
    renderer:
      unsafe: true